node_js:
  - "node"
  - "6"
  - "8"
  - "10"

sudo: false

script:
  - npm install
  - npm run test

after_script:
  - "npm install coveralls"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
